version: "3"
services:
  # mongo_db:
  #   image: mongo:latest
  #   restart: always
  #   ports:
  #     - 27018:27017
  #   expose:
  #     - 27017

  # backend:
  #   build:
  #     context: ../Server
  #     dockerfile: Dockerfile
  #   restart: always
  #   environment:
  #     PORT: 4000
  #     BASE_URL_CLIENT: http://localhost
  #     JWT_ACCESS_KEY: ducanh123
  #     JWT_REFRESH_KEY: ducanh2211
  #     DB_URI: mongodb+srv://dogotrieu:M7L0tWGgulKzDTLO@dogotrieu.tus5r.mongodb.net/dogotrieu_database
  #   depends_on:
  #     - mongo_db
  #   ports:
  #     - 4000:4000
  #   expose:
  #     - 4000

  nextjs:
    build:
      context: ../Client
      dockerfile: Dockerfile.prod
    restart: always
    env_file:
      - ../Client/.env
    # environment:
    #   NODE_ENV: production
    ports:
      - 3000:3000
    expose:
      - 3000

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - nextjs
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: always
