version: "3"
services:
  backend:
    build:
      context: ../Server
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 4000
      BASE_URL_CLIENT: http://localhost
    ports:
      - 4000:4000
    expose:
      - 4000

  nextjs:
    build:
      context: ../Client
      dockerfile: Dockerfile.prod
    restart: always
    env_file:
      - ../Client/.env
    ports:
      - 3000:3000
    expose:
      - 3000

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - nextjs
      - backend
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: always
