version: "3"
services:
  backend:
    build:
      context: ../Server
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 4000
      BASE_URL_CLIENT: http://localhost
    ports:
      - 4000:4000
    expose:
      - 4000

  nextjs:
    build:
      context: ../Client
      dockerfile: Dockerfile.prod
    restart: always
    env_file:
      - ../Client/.env
    ports:
      - 3000:3000
    expose:
      - 3000

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443 # Cổng cho HTTPS
    depends_on:
      - nextjs
      - backend
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./private.key:/etc/nginx/certs/private.key # Ánh xạ private.key
      - ./public.pem:/etc/nginx/certs/public.pem # Ánh xạ public.pem
      - ./origin_ca_rsa_root.pem:/etc/nginx/certs/origin_ca_rsa_root.pem # Ánh xạ origin_ca_rsa_root.pem
    restart: always
